# Generated by Django 3.1.5 on 2021-03-07 04:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('adresse_postale', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Cursus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Faculte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('couleur', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='personne',
            name='amis',
            field=models.ManyToManyField(related_name='_personne_amis_+', to='book.Personne'),
        ),
        migrations.AddField(
            model_name='personne',
            name='courriel',
            field=models.EmailField(default=datetime.datetime(2021, 3, 7, 4, 37, 16, 818888, tzinfo=utc), max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personne',
            name='date_de_naissance',
            field=models.DateField(default=datetime.datetime(2021, 3, 7, 4, 37, 48, 905611, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personne',
            name='id',
            field=models.AutoField(auto_created=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personne',
            name='matricule',
            field=models.CharField(default=datetime.datetime(2021, 3, 7, 4, 38, 22, 324372, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personne',
            name='nom',
            field=models.CharField(default=datetime.datetime(2021, 3, 7, 4, 38, 26, 883722, tzinfo=utc), max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personne',
            name='prenom',
            field=models.CharField(default=datetime.datetime(2021, 3, 7, 4, 38, 31, 275136, tzinfo=utc), max_length=30),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_de_publication', models.DateField()),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.personne')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='book.personne')),
                ('annee', models.IntegerField()),
                ('cursus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.cursus')),
            ],
            bases=('book.personne',),
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='book.personne')),
                ('bureau', models.CharField(max_length=30)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.campus')),
                ('fonction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.fonction')),
            ],
            bases=('book.personne',),
        ),
        migrations.AddField(
            model_name='personne',
            name='faculte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.fonction'),
            preserve_default=False,
        ),
    ]
