# Generated by Django 3.1.5 on 2021-03-07 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20210307_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='faculte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.faculte'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
